name: receipt-automation
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: ra-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - WEBHOOK_URL=${N8N_WEBHOOK_TUNNEL_URL}
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - n8n-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ra-ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      n8n:
        condition: service_healthy
    command:
      - http
      - n8n:5678
      - --log=stdout
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge